version: 0.1
phases:
  install:
    commands:
      - npm install
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket oddly.shaped.dog 
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
